export const runtime = "nodejs";
export const dynamic = "force-dynamic";

import { NextRequest, NextResponse } from "next/server";
import { rateLimit, RATE_LIMITS } from "@/lib/rateLimiter";

export async function POST(req: NextRequest) {
  try {
    // Apply rate limiting
    const rateLimitResponse = await rateLimit(req, RATE_LIMITS.PDF_EXPORT);
    if (rateLimitResponse) {
      return rateLimitResponse;
    }

    const { title = "CareIQ Chat Export", messages = [] } = await req.json();

    // Create HTML content that can be printed as PDF
    let messagesHtml = '';
    
    for (const message of messages) {
      const role = message.role || 'user';
      const roleLabel = role === 'user' ? 'You' : role === 'assistant' ? 'CareIQ' : 'System';
      const roleClass = role.toLowerCase();
      
      messagesHtml += `
        <div class="message ${roleClass}">
          <div class="message-role">${roleLabel}:</div>
          <div class="message-content">${(message.content || '').replace(/\n/g, '<br>')}</div>
        </div>
      `;
    }

    const htmlContent = `
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>${title}</title>
    <style>
        @page { 
            size: A4; 
            margin: 1in; 
        }
        body { 
            font-family: Arial, sans-serif; 
            font-size: 12px; 
            line-height: 1.4; 
            margin: 0; 
            padding: 0;
            color: #333;
        }
        .header { 
            font-size: 18px; 
            font-weight: bold; 
            margin-bottom: 10px; 
            color: #1E40AF;
        }
        .export-date {
            font-size: 9px;
            color: #666;
            margin-bottom: 20px;
        }
        .message {
            margin-bottom: 15px;
            padding: 12px;
            border-left: 3px solid #3B82F6;
            background: #F8FAFC;
            break-inside: avoid;
        }
        .message-role {
            font-weight: bold;
            color: #1E40AF;
            margin-bottom: 5px;
            font-size: 11px;
        }
        .message-content {
            white-space: pre-wrap;
            word-wrap: break-word;
        }
        .user { 
            border-left-color: #10B981; 
            background: #F0FDF4;
        }
        .user .message-role {
            color: #059669;
        }
        .assistant { 
            border-left-color: #3B82F6; 
            background: #F8FAFC;
        }
        .assistant .message-role {
            color: #1E40AF;
        }
        .system { 
            border-left-color: #F59E0B; 
            background: #FFFBEB;
        }
        .system .message-role {
            color: #D97706;
        }
        
        /* Print-specific styles */
        @media print {
            .message {
                page-break-inside: avoid;
            }
            body {
                font-size: 11px;
            }
        }
    </style>
</head>
<body>
    <div class="header">${title}</div>
    <div class="export-date">Exported: ${new Date().toLocaleString()}</div>
    
    ${messagesHtml}
    
    <div style="margin-top: 30px; padding-top: 20px; border-top: 1px solid #E5E7EB; font-size: 10px; color: #6B7280;">
        Generated by CareIQ • ${messages.length} message${messages.length !== 1 ? 's' : ''} • ${new Date().toLocaleDateString()}
    </div>
</body>
</html>`;

    // Return HTML content that can be printed as PDF by the browser
    return new NextResponse(htmlContent, {
      headers: {
        'Content-Type': 'text/html',
        'Content-Disposition': `inline; filename="${title.replace(/[^a-zA-Z0-9]/g, '-')}-${new Date().toISOString().split('T')[0]}.html"`,
      },
    });

  } catch (error: any) {
    console.error("Export error:", error);
    return NextResponse.json({ 
      ok: false, 
      error: error.message || "Failed to export chat" 
    }, { status: 500 });
  }
}